### ISSUE TITLE
Memory Leak in Lager [JIRA: RIAK-2132]

### ISSUE THREAD

**Issue by LeoKudrik** [basho/lager#288] opened 2015-08-20 18:01 UTC
With active record in the log I see the memory increase. Are you familiar with the memory leak issue in lager? When you turn off the lager issue is fixed.

![screenshot - 20 08 2015 - 19 20 47](https://cloud.githubusercontent.com/assets/362985/9391250/60ad451e-477e-11e5-8a61-961d4c7f1cde.png)
```
    {lager, [
        {handlers, [
            {lager_console_backend, debug},
            {lager_file_backend, [
                {file, "log/error.log"},
                {level, warning}
            ]},
            {lager_file_backend, [
                {file, "log/console.log"},
                {level, info}
            ]}
        ]},
        {crash_log, "log/crash.log"},
        {colored, true},
        {colors, [
            {debug, "\e[0;38m"},
            {info, "\e[0;32m"},
            {notice, "\e[1;36m"},
            {warning, "\e[1;33m"},
            {error, "\e[1;31m"}
        ]},
        {error_logger_hwm, 550}
    ]},
```

**Comment by reith** [comment] 2015-08-27 12:49
We affected by this too.

**Comment by chwevans** [comment] 2015-09-05 00:19
I have noticed this as well with the following configuration.
```
  {lager, [
    {handlers, [
      {lager_console_backend, [info, {lager_default_formatter, [time, " [",severity,"] ", {pid, ""}, {module, ["@", module, ":"], ""}, {function, [function, ":"], ""}, {line, ""}, " ", message, "\n"]}]}
    ]}  
  ]}, 
```

Increasing the log level solves the problem as it eliminates the majority of the logs. Observing the node while the problem is happening reveals that lager_event is holding onto the memory despite the message queue not backing up. This seems like it might be a binary memory leak.

**Comment by reith** [comment] 2015-09-05 04:15
We removed whole `lager_console_backend` in our production profile's `environment and It served well for several days.

**Comment by chwevans** [comment] 2015-09-05 06:01
The problem does seem to only manifest with the console backend. I noticed no memory consumption with the file backend.

**Comment by jonmeredith** [comment] 2015-09-05 18:23
In case it's useful, in the past I've seen interesting hangs in the VM waiting on console output on Solaris and it's derivatives (SmartOS) which cleared when I attached direct to the VM over the 'to_erl' pipe and hit a few carriage returns.  I haven't seen it on other platforms to date, but we disabled the console backend for Riak in production so there would be less chance of it happening.

**Comment by JeetKunDoug** [comment] 2015-09-06 03:16
Can you let us know what version of Erlang you're using as well please? The connection to the console backend suggests it may also be a known issue with Erlang 18 (OTP-12941) that was fixed with Erlang 18.03 - If you're running 18, but not 18.03, could you upgrade your application and see if the problem persists?

**Comment by chwevans** [comment] 2015-09-06 05:44
I was using 18.0, running a small test on 18.0. 3 it appears that the memory leak is gone.

**Comment by LeoKudrik** [comment] 2015-09-08 09:28
18.0.3 solves the problem, thanks

**Comment by JeetKunDoug** [comment] 2015-09-08 13:12
Thanks for the follow-up. Given the confirmations that 18.03 seems to solve the issue, and the know issue in Erlang 18 < 18.03, I'm going to close this issue for now. If anyone is seeing this in other Erlang versions, please reopen this and we'll take a more in-depth look at the issue.

**Closed by JeetKunDoug** 2015-09-08 13:12 UTC
Labels: JIRA: To Do

**Comment by Basho-JIRA** [comment] 2015-09-17 17:54
This was caused by an issue in Erlang 18, before 18.03, where the console implementation had a memory leak - closed unless someone can reproduce it outside of the affected Erlang releases. 

***[posted via JIRA by Douglas Rohrer]***
