### ISSUE TITLE
Warning: lager:status/0 calls undefined function lager_default_tracer:info/1 (Xref) [JIRA: RIAK-1892]

### ISSUE THREAD

**Issue by lispking** [basho/lager#238] opened 2014-10-26 10:51 UTC
rt

**Comment by mrallen1** [comment] 2015-06-24 19:58
I can't reproduce this locally.

**Comment by mrallen1** [comment] 2016-01-27 21:51
Closing this for now. Please reopen if we missed something. Thanks.

**Closed by mrallen1** 2016-01-27 21:51 UTC
Labels: JIRA: To Do
