### ISSUE TITLE
function_clause error msgs on 3.0.0 version. [JIRA: RIAK-2042]

### ISSUE THREAD

**Issue by snaiper80** [basho/lager#280] opened 2015-07-24 03:07 UTC
I tried to upgrade the lager's version in my projects to tag 3.0.0

But I got a some crash log on console as below.
How can I fix this error? No issues on lager 2.X.

```
Erlang/OTP 17 [erts-6.4.1] [source-381fb6c] [64-bit] [smp:2:2] [async-threads:6] [hipe] [kernel-poll:true]


=ERROR REPORT==== 24-Jul-2015::11:51:28 ===
** gen_event handler log_mf_h crashed.
** Was installed in error_logger
** Last event was: get_loglevel
** When handler state == {state,"log/sasl",10485760,5,25753,5,
                                {file_descriptor,prim_file,{#Port<0.5227>,18}},
                                [],#Fun<sasl.0.89613933>}
** Reason == {function_clause,
                 [{log_mf_h,handle_call,
                      [get_loglevel,
                       {state,"log/sasl",10485760,5,25753,5,
                           {file_descriptor,prim_file,{#Port<0.5227>,18}},
                           [],#Fun<sasl.0.89613933>}],
                      [{file,"log_mf_h.erl"},{line,164}]},
                  {gen_event,server_call_update,3,
                      [{file,"gen_event.erl"},{line,638}]},
                  {gen_event,server_call,4,
                      [{file,"gen_event.erl"},{line,587}]},
                  {gen_event,handle_msg,5,[{file,"gen_event.erl"},{line,258}]},
                  {proc_lib,init_p_do_apply,3,
                      [{file,"proc_lib.erl"},{line,237}]}]}

=ERROR REPORT==== 24-Jul-2015::11:51:28 ===
** gen_event handler sasl_report_file_h crashed.
** Was installed in error_logger
** Last event was: get_loglevel
** When handler state == {<0.1297.0>,"log/sasl-error.log",error}
** Reason == {error,bad_query}
Eshell V6.4.1  (abort with ^G)
(bird@127.0.0.1)1>
```

my sys.config file is...
```
[
 %% SASL config
 {sasl, [
         {sasl_error_logger, {file, "log/sasl-error.log"}},
         {errlog_type, error},
         {error_logger_mf_dir, "log/sasl"},      % Log directory
         {error_logger_mf_maxbytes, 10485760},   % 10 MB max file size
         {error_logger_mf_maxfiles, 5}           % 5 files max
        ]},

 %% Lager config
 {lager, [

      %% Installed Handlers
      {handlers, [
            {lager_file_backend, [
                {file, "log/trace.log"}, { level, debug },  { size, 10737418240 }, { date, "$D0" }, { count, 30 }]},
            {lager_file_backend, [
                {file, "log/access.log"},  { level, none },  { size, 10737418240 }, { date, "$M1D0" }, { count, 30 }, { formatter_config, [date, " ", time, " ", message, "\n"] }]},
            {lager_kafka_backend, [
                {level, none}, {topic, <<"xyz">>}, {broker, {"kafka.xyz.com", 9092 }}, {formatter_config, [date, " ", time, " ", message]}, {ekaf_per_partition_workers, 5}, {ekaf_partition_strategy, random}]}
      ]},

      {traces, [
            { {lager_file_backend, "log/access.log"}, [{request, access}], info},
            { lager_kafka_backend, [{request, access}], info}
      ]},

      %% What colors to use with what log levels
      {colored, true},

      %% async threshold
      {async_threshold, 100},
      {async_threshold_window, 20}
    ]},

   ...
```

Is my configuration something wrong?

**Comment by macintux** [comment] 2015-07-24 12:37
It looks like your Kafka backend for lager is invoking `get_loglevel`, which has changed with the new release. Can you point me to the source?

**Comment by snaiper80** [comment] 2015-07-24 16:38
Umm... OK I will try to check the source. 
Ah! source repo is https://github.com/snaiper80/lager_kafka_backend
Thank you!

**Comment by snaiper80** [comment] 2015-07-27 01:56
I tried to remove all kafka dependencies from sources, also.. sys.config. 
But I got the same issue. :(

umm..ok.. I will try to check lager srcs.

**Comment by macintux** [comment] 2015-07-27 01:58
I will take a closer look too. Thank you for following up.

**Comment by snaiper80** [comment] 2015-07-27 02:38
(First, sorry for my poor english)

I am looking this issue by old-fashioned print :)
Below is my print logs.

```erlang
Erlang/OTP 17 [erts-6.4.1] [source-381fb6c] [64-bit] [smp:2:2] [async-threads:6] [hipe] [kernel-poll:true]

lager_handler_watcher:init(lager_event, lager_backend_throttle, [100,20]) is called
lager_handler_watcher:install_handler2 Lager installed handler lager_backend_throttle into lager_event
lager:update_loglevel_config(lager_event) is called.
lager:get_loglevels(lager_event) is called
lager_handler_watcher:init(lager_event, {lager_file_backend,"log/trace.log"}, [{file,
                                                                                "log/trace.log"},
                                                                               {level,
                                                                                info},
                                                                               {size,
                                                                                10485760},
                                                                               {date,
                                                                                "$D0"},
                                                                               {count,
                                                                                30},
                                                                               {high_water_mark,
                                                                                9999}]) is called
lager_handler_watcher:install_handler2 Lager installed handler {lager_file_backend,
                                                                "log/trace.log"} into lager_event
lager:update_loglevel_config(lager_event) is called.
lager:get_loglevels(lager_event) is called
lager_handler_watcher:init(lager_event, {lager_file_backend,"log/access.log"}, [{file,
                                                                                 "log/access.log"},
                                                                                {level,
                                                                                 none},
                                                                                {size,
                                                                                 10485760},
                                                                                {date,
                                                                                 "$M1D0"},
                                                                                {count,
                                                                                 30},
                                                                                {formatter_config,
                                                                                 [date,
                                                                                  " ",
                                                                                  time,
                                                                                  " ",
                                                                                  message,
                                                                                  "\n"]}]) is called
lager_handler_watcher:install_handler2 Lager installed handler {lager_file_backend,
                                                                "log/access.log"} into lager_event
lager:update_loglevel_config(lager_event) is called.
lager:get_loglevels(lager_event) is called
lager_handler_watcher:init(lager_event, lager_kafka_backend, [{level,none},
                                                              {topic,
                                                               <<"xxx">>},
                                                              {broker,
                                                               {"kafka.xyz.com",
                                                                9092}},
                                                              {formatter_config,
                                                               [date," ",time,
                                                                " ",message]},
                                                              {ekaf_per_partition_workers,
                                                               5},
                                                              {ekaf_partition_strategy,
                                                               random}]) is called
lager:update_loglevel_config(lager_event) is called.
lager:get_loglevels(lager_event) is called
lager_app:start_error_logger_handler(_, 50, {ok,[]}) is called
lager_handler_watcher:init(error_logger, error_logger_lager_h, [50,handle]) is called
lager_handler_watcher:install_handler2 Lager installed handler error_logger_lager_h into error_logger
lager:update_loglevel_config(error_logger) is called.
lager:get_loglevels(error_logger) is called

=ERROR REPORT==== 27-Jul-2015::11:26:23 ===
** gen_event handler log_mf_h crashed.
** Was installed in error_logger
** Last event was: get_loglevel
** When handler state == {state,"log/sasl",10485760,5,9299,1,
                                {file_descriptor,prim_file,{#Port<0.5071>,18}},
                                [],#Fun<sasl.0.89613933>}
** Reason == {function_clause,
                 [{log_mf_h,handle_call,
                      [get_loglevel,
                       {state,"log/sasl",10485760,5,9299,1,
                           {file_descriptor,prim_file,{#Port<0.5071>,18}},
                           [],#Fun<sasl.0.89613933>}],
                      [{file,"log_mf_h.erl"},{line,164}]},
                  {gen_event,server_call_update,3,
                      [{file,"gen_event.erl"},{line,638}]},
                  {gen_event,server_call,4,
                      [{file,"gen_event.erl"},{line,587}]},
                  {gen_event,handle_msg,5,[{file,"gen_event.erl"},{line,258}]},
                  {proc_lib,init_p_do_apply,3,
                      [{file,"proc_lib.erl"},{line,237}]}]}

=ERROR REPORT==== 27-Jul-2015::11:26:23 ===
** gen_event handler sasl_report_file_h crashed.
** Was installed in error_logger
** Last event was: get_loglevel
** When handler state == {<0.1263.0>,"log/sasl-error.log",error}
** Reason == {error,bad_query}
```

OK.  why 'error_logger'? maybe this calling seq is cause of this issue.
```erlang
lager_app:start_error_logger_handler(_, 50, {ok,[]}) is called
lager_handler_watcher:init(error_logger, error_logger_lager_h, [50,handle]) is called
lager_handler_watcher:install_handler2 Lager installed handler error_logger_lager_h into error_logger
lager:update_loglevel_config(error_logger) is called.
lager:get_loglevels(error_logger) is called
```

After more checking codes, 'error_logger' is came from this.
(https://github.com/basho/lager/blob/master/src/lager_app.erl?#L149)

```
case supervisor:start_child(lager_handler_watcher_sup, [error_logger, error_logger_lager_h, [HWM, GlStrategy]]) of

```

Umm..maybe something in sys.config is wrong?

**Comment by macintux** [comment] 2015-07-27 17:23
Thank you for your invaluable assistance. I greatly appreciate the work you applied to this problem, and your analysis is very good.

This is probably not the final patch, but please try this branch to see if it works for you: https://github.com/basho/lager/tree/bugfix/jrd/280

If the diff is easier to apply:

```
--- a/src/lager.erl
+++ b/src/lager.erl
@@ -469,6 +469,10 @@ add_trace_to_loglevel_config(Trace, Sink) ->
     end.

 %% @doc recalculate min log level
+update_loglevel_config(error_logger) ->
+    %% Not a sink under our control, part of the Erlang logging
+    %% utility that error_logger_lager_h attaches to
+    true;
 update_loglevel_config(Sink) ->
     {_, Traces} = lager_config:get({Sink, loglevel}, {ignore_me, []}),
     MinLog = minimum_loglevel(get_loglevels(Sink)),
```

**Comment by mrallen1** [comment] 2015-07-27 21:12
@macintux and I have been talking about this issue and I would expect an official fix for it soon. I want to write a test case for this problem before we push the fix in.

**Comment by mrallen1** [comment] 2015-07-27 21:15
Incidentally the root cause of this crash is that in the 2.x branch, `lager:get_loglevels` is **only** concerned with `lager_event` and the sink name is hardcoded. When we added multiple sinks in 3.0, we have to tell lager what sink we want to lookup for its current level.  The OTP supplied sink `error_logger` needs its own special case since none of the OTP supplied logging handlers have any notion of a lager-style "loglevel" much less code to return the current level.  So your analysis was right on, but the error is in lager, not in your SASL configuration.

Thanks again for the ticket.

**Comment by snaiper80** [comment] 2015-07-28 00:39
@macintux Awesome!! After I apply that patch branch, I have no issue. Thank you! 
@mrallen1 OK. I will wait the final patch on production environment. 

Thanks for your attention. :+1:

**Comment by mrallen1** [comment] 2015-07-30 01:31
OK, 3.0.1 is tagged and pushed, and it contains a fix for this issue. Thanks for the ticket and all of your work diagnosing the issue. :smile:

**Closed by mrallen1** 2015-07-30 01:31 UTC
Labels: JIRA: To Do
