### ISSUE TITLE
log not complete [JIRA: RIAK-1902]

### ISSUE THREAD

**Issue by dcy** [basho/lager#257] opened 2015-04-13 13:20 UTC
21:15:56.515 [error] Error in process <0.427.0> on node 'sanguo_1@192.168.1.236' with exit value: {{badmatch,#{generals=>[#{equipment_infos=>[#{equipment_id=>0,equipment_tid=>4217,level=>37},#{equipment_id=>0,equipment_tid=>2212,level=>20},#{equipment_id=>0,equipment_tid=>3211,level=>1}],favor_level=>28,general_id=>-5,general_tid=>72,level=>40,skill_group_infos... 

The log is not complete, instead of "...", How can i make it complete?

**Comment by slfritchie** [comment] 2015-04-13 13:33
Have you tried the configuration suggested at https://github.com/basho/lager#setting-the-truncation-limit-at-compile-time ?

**Comment by dcy** [comment] 2015-04-13 13:47
My rebar.config is:
{erl_opts, [{parse_transform, lager_transform}, {lager_truncation_size, 102400}]}.
And the log is:
21:46:18.724 [error] Error in process <0.427.0> on node 'sanguo_1@192.168.1.236' with exit value: {{badmatch,#{generals=>[#{equipment_infos=>[#{equipment_id=>0,equipment_tid=>1202,level=>9},#{equipment_id=>0,equipment_tid=>2216,level=>59},#{equipment_id=>0,equipment_tid=>3202,level=>13},#{equipment_id=>0,equipment_tid=>4212,level=>19}],favor_level...

**Comment by zdaniel86** [comment] 2015-04-13 14:22
This error is reported by "emulator" process. Truncation is performed not by lager but by erlang itself. You cannot control truncation size for this type of errors.

**Comment by dcy** [comment] 2015-04-14 08:35
Does it mean it can not work now?
It is not convenient to debug.

**Comment by Basho-JIRA** [comment] 2015-04-20 17:49
21:15:56.515 [error] Error in process <0.427.0> on node 'sanguo_1@192.168.1.236' with exit value: {{badmatch,#{generals=>[#{equipment_infos=>[#{equipment_id=>0,equipment_tid=>4217,level=>37},#{equipment_id=>0,equipment_tid=>2212,level=>20},#{equipment_id=>0,equipment_tid=>3211,level=>1}],favor_level=>28,general_id=>-5,general_tid=>72,level=>40,skill_group_infos...

The log is not complete, instead of "...", How can i make it complete? 

***[posted via JIRA by Derek Somogyi]***

**Comment by mrallen1** [comment] 2015-06-24 21:35
You may need to patch `error_logger_lager_h` - by default it has a hard coded limit of 100 or 500 characters for most log messages.  We plan to make that fully configurable in the future, but for now, you'd have to change it in the Erlang code, recompile the beam and hot load it into your emulator.

See for example: https://github.com/basho/lager/blob/master/src/error_logger_lager_h.erl#L399

**Comment by mrallen1** [comment] 2015-06-24 21:37
This is a duplicate of #162

**Closed** 2015-11-13 18:16 UTC
Labels: JIRA: Done

**Comment by Basho-JIRA** [comment] 2015-12-04 03:49
Ummm, this GH issue was closed on June 25, 2015. Closing in JIRA. 

***[posted via JIRA by Scott Fritchie]***
